const Map<String, String> en = {
  'appTitle': 'GizmoGlobe',
  'welcomeBack': 'Welcome back,',
  'overview': 'Overview',
  'products': 'Products',
  'customers': 'Customers',
  'revenue': 'Revenue',
  'avgIncome': 'Avg. Income',
  'monthlySales': 'Monthly Sales',
  'dailySales': 'Daily Sales',
  'monthly': 'Monthly',
  'daily': 'Daily',
  'last12Months': 'Last 12 months',
  'last3Months': 'Last 3 months',
  'newIncomingInvoice': 'Restock',
  'selectManufacturer': 'Select Manufacturer',
  'addProduct': 'Add Product',
  'invoiceDetails': 'Invoice Details',
  'importPrice': 'Import Price',
  'quantity': 'Quantity',
  'totalPrice': 'Total Price: ',
  'paymentStatus': 'Payment Status',
  'paymentMethod': 'Payment Method',
  'createInvoice': 'Create Invoice',
  'cancel': 'Cancel',
  'add': 'Add',
  'editProductDetail': 'Edit Product Detail',
  'update': 'Update',
  'createInvoiceSuccess': 'Invoice created successfully.',
  'editInvoiceSuccess': 'Invoice edited successfully.',
  'createIncomingInvoiceSuccess': 'Incoming invoice created successfully.',
  'updateIncomingInvoiceSuccess': 'Incoming invoice updated successfully.',
  'searchIncomingInvoices': 'Find incoming invoices...',
  'noIncomingInvoicesFound': 'No incoming invoices found',
  'view': 'View',
  'editPayment': 'Edit Payment',
  'onlyUnpaidCanBeMarkedPaid': 'Only unpaid invoices can be marked as paid',
  'markAsPaidQuestion': 'Mark this invoice as paid?',
  'confirm': 'OK',
  'sortBy': 'Sort By ',
  'dateNewestFirst': 'Date (Newest First)',
  'dateOldestFirst': 'Date (Oldest First)',
  'priceHighestFirst': 'Price (Highest First)',
  'priceLowestFirst': 'Price (Lowest First)',
  'errorOccurred': 'Error occurred',
  'newInvoice': 'New Invoice',
  'customerInformation': 'Customer Information',
  'selectCustomer': 'Select customer',
  'customer': 'Customer',
  'pleaseSelectCustomer': 'Please select a customer',
  'address': 'Address',
  'pleaseSelectAddress': 'Please select an address',
  'salesStatus': 'Sales Status',
  'totalAmount': 'Total Amount',
  'noProductsAddedYet': 'No products added yet',
  'noProductsAvailableForManufacturer':
      'No products available for this manufacturer',
  'price': 'Price',
  'availableStock': 'Available stock',
  'pleaseSelectCustomerFirst': 'Please select a customer first',
  'searchSalesInvoices': 'Find sales invoices...',
  'noSalesInvoicesFound': 'No sales invoices found',
  'warrantyReceipt': 'Warranty #{id}',
  'warrantyInformation': 'Warranty Information',
  'status': 'Status',
  'reasonForWarranty': 'Reason for Warranty',
  'productsUnderWarranty': 'Products Under Warranty',
  'unknownCategory': 'Unknown Category',
  'unknown': 'Unknown',
  'updateWarrantyStatus': 'Update Warranty Status',
  'confirmStatusUpdate': 'Confirm Status Update',
  'areYouSureChangeStatus':
      'Are you sure you want to change the status to {status}?',
  'save': 'Save',
  'updateStatus': 'Update Status',
  'noSalesInvoicesAvailable': 'No sales invoices available',
  'noEligibleSalesInvoices':
      'This customer has no eligible sales invoices for warranty claims.',
  'pleaseSelectSalesInvoice': 'Please select a sales invoice',
  'reasonForWarrantyLabel': 'Reason for Warranty',
  'selectProductsForWarranty': 'Select Products for Warranty',
  'warrantyInvoiceCreated': 'Warranty invoice created successfully',
  'errorCreatingWarrantyInvoice': 'Error creating warranty invoice: {error}',
  'product': 'Product',
  'selectProduct': 'Select product',
  'pleaseSelectProduct': 'Please select a product',
  'quantityGreaterThanZero': 'Quantity must be greater than 0',
  'notEnoughStock': 'Not enough stock',
  'noAddressFound': 'No address found',
  'date': 'Date',
  'subtotal': 'Subtotal',
  'editInvoice': 'Edit Invoice',
  'changeAddress': 'Change Address',
  'unknownProduct': 'Unknown Product',
  'errorWithMessage': 'Error: {error}',
  'errorLoadingInvoiceDetails': 'Error loading invoice details: {error}',
  'salesInvoice': 'Sales Invoice',
  'loading': 'Loading...',
  'productInfoLoading': 'Product info loading',
  'category': 'Category',
  'enterAddress': 'Enter Address',
  'findWarrantyInvoices': 'Find warranty invoices...',
  'noWarrantyInvoicesFound': 'No warranty invoices found',
  'markAsCompleted': 'Mark as Completed',
  'errorLoadingWarrantyInvoiceDetails':
      'Error loading warranty invoice details: {error}',
  'sales': 'Sales',
  'incoming': 'Incoming',
  'warranty': 'Warranty',
  'hello': 'Hello!',
  'contactUs': 'Contact Us:',
  'logOut': 'Log out',
  'home': 'Home',
  'invoice': 'Invoice',
  'stakeholder': 'Stakeholder',
  'voucher': 'Voucher',
  'profile': 'Profile',
  'addNewAddress': 'Add New Address',
  'receiverName': 'Receiver Name',
  'enterReceiverName': 'Enter receiver name',
  'receiverPhone': 'Receiver Phone',
  'enterPhoneNumber': 'Enter phone number',
  'location': 'Location',
  'streetAddress': 'Street Address',
  'streetNameBuildingHouseNo': 'Street name, building, house no.',
  'addAddress': 'Add Address',
  'customerDetail': 'Customer Detail',
  'edit': 'Edit',
  'name': 'Name',
  'email': 'Email',
  'phone': 'Phone',
  'addresses': 'Addresses',
  'pleaseFillInAllRequiredFields': 'Please fill in all required fields',
  'discardChanges': 'Discard Changes?',
  'unsavedChangesDiscard':
      'You have unsaved changes. Do you want to discard them?',
  'discard': 'DISCARD',
  'editCustomer': 'Edit Customer',
  'fullName': 'Full Name',
  'nameIsRequired': 'Name is required',
  'nameMin2Chars': 'Name must be at least 2 characters',
  'phoneNumber': 'Phone Number',
  'phoneNumberIsRequired': 'Phone number is required',
  'pleaseEnterValidPhoneNumber': 'Please enter a valid phone number',
  'addNewCustomer': 'Add New Customer',
  'addCustomer': 'Add Customer',
  'pleaseFillInAllFields': 'Please fill in all fields',
  'customerAddedSuccessfully': 'Customer added successfully',
  'findCustomers': 'Find customers...',
  'noMatchingCustomersFound': 'No matching customers found',
  'employeeDetail': 'Employee Detail',
  'employeeInformation': 'Employee Information',
  'role': 'Role',
  'delete': 'Delete',
  'deleteEmployee': 'Delete Employee',
  'areYouSureDeleteEmployee': 'Are you sure you want to delete this employee?',
  'editEmployee': 'Edit Employee',
  'pleaseEnterName': 'Please enter a name',
  'pleaseEnterPhoneNumber': 'Please enter a phone number',
  'pleaseSelectRole': 'Please select a role',
  'addNewEmployee': 'Add New Employee',
  'pleaseEnterEmail': 'Please enter email address',
  'filterByRole': 'Filter by Role',
  'clearFilter': 'Clear Filter',
  'findEmployees': 'Find employees...',
  'noEmployeesFound': 'No employees found',
  'employeeAddedSuccessfully': 'Employee added successfully.',
  'employeeUpdatedSuccessfully': 'Employee updated successfully.',
  'employeeDeletedSuccessfully': 'Employee deleted successfully.',
  'customerUpdatedSuccessfully': 'Customer updated successfully.',
  'manufacturerUpdatedSuccessfully': 'Manufacturer updated successfully.',
  'manufacturerDeactivatedSuccessfully': 'Manufacturer deactivated successfully.',
  'manufacturerActivatedSuccessfully': 'Manufacturer activated successfully.',
  'failedToToggleManufacturerStatus': 'Failed to toggle manufacturer status: {error}',
  'failedToUpdateManufacturer': 'Failed to update manufacturer: {error}',
  'failedToUpdateEmployee': 'Failed to update employee: {error}',
  'failedToDeleteEmployee': 'Failed to delete employee: {error}',
  'failedToUpdateCustomer': 'Failed to update customer: {error}',
  'manufacturerDetail': 'Manufacturer Detail',
  'deactivate': 'Deactivate',
  'activate': 'Activate',
  'deactivateManufacturer': 'Deactivate Manufacturer',
  'activateManufacturer': 'Activate Manufacturer',
  'deactivateManufacturerConfirm':
      'Are you sure you want to deactivate this manufacturer?',
  'activateManufacturerConfirm':
      'Are you sure you want to activate this manufacturer?',
  'inactive': 'Inactive',
  'manufacturerInformation': 'Manufacturer Information',
  'manufacturerName': 'Manufacturer Name',
  'editManufacturer': 'Edit Manufacturer',
  'addNewManufacturer': 'Add New Manufacturer',
  'addManufacturer': 'Add Manufacturer',
  'findManufacturers': 'Find manufacturers...',
  'noMatchingManufacturersFound': 'No matching manufacturers found',
  'manufacturerAddedSuccessfully': 'Manufacturer added successfully',
  'deactivateManufacturerConfirmName':
      'Are you sure you want to deactivate {name}?',
  'activateManufacturerConfirmName':
      'Are you sure you want to activate {name}?',
  'employees': 'Employees',
  'vendors': 'Vendors',
  'appAvatar': 'App Avatar',
  'createNewAccount': 'Create new account',
  'alreadyHaveAccount': 'Already have an account?',
  'informationTitle': 'Information',
  'aboutGizmoGlobe': 'About GizmoGlobe',
  'aboutUsTitle': 'About Us',
  'aboutUsContent':
      'GizmoGlobe is your trusted provider for computer hardware solutions.',
  'ourMissionTitle': 'Our Mission',
  'ourMissionContent':
      'To provide excellent service and quality products to you, our beloved customers.',
  'contactInformationTitle': 'Contact Information',
  'contactInformationContent': 'Address: UIT',
  'businessHoursTitle': 'Business Hours',
  'businessHoursContent':
      'Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 4:00 PM\nSunday: Closed',
  'supportTitle': 'Support',
  'supportMembers': 'Members of teams',
  'supportRoleDeveloper': 'Developer',
  'supportStudentId': 'Student ID: {id}',
  'supportRole': 'Role: {role}',
  'supportEmail': 'Email: {email}',
  'accountSettings': 'Account Settings',
  'editProfile': 'Edit Profile',
  'updatePersonalInfo': 'Update your personal information',
  'changePassword': 'Change Password',
  'manageAccountSecurity': 'Manage your account security',
  'signOut': 'Sign Out',
  'username': 'Username',
  'saveChanges': 'Save changes',
  'updateProfileSuccess': 'Update profile successfully',
  'passwordResetEmailWillBeSent':
      'A password reset email will be sent to {email}',
  'passwordResetEmailSentSuccess': 'Password reset email sent successfully',
  'sendPasswordResetEmail': 'Send Password Reset Email',
  'noUserSignedIn': 'No user is currently signed in',
  'addVoucher': 'Add Voucher',
  'basicInformation': 'Basic Information',
  'voucherName': 'Voucher Name',
  'minimumPurchase': 'Minimum purchase',
  'startTime': 'Start Time',
  'maxUsagePerPerson': 'Max Usage Per Person',
  'description': 'Description',
  'voucherSettings': 'Voucher Settings',
  'discountType': 'Discount Type',
  'fixedAmount': 'Fixed Amount',
  'percentage': 'Percentage',
  'maximumDiscountValue': 'Maximum Discount Value',
  'usageLimit': 'Usage Limit',
  'unlimited': 'Unlimited',
  'limited': 'Limited',
  'maximumUsage': 'Maximum Usage',
  'usageLeft': 'Usage left',
  'timeLimit': 'Time Limit',
  'noEndTime': 'No End Time',
  'hasEndTime': 'Has End Time',
  'endTime': 'End Time',
  'voucherWillNotExpire': 'This voucher will not expire',
  'visibility': 'Visibility',
  'hidden': 'Hidden',
  'visible': 'Visible',
  'disabled': 'Disabled',
  'enabled': 'Enabled',
  'selectField': 'Select {field}',
  'enterField': 'Enter {field}',
  'all': 'All',
  'warningText': 'Warning: ',
  'enableLocationServices': 'Enable location services in Settings',
  'noLocationsAvailable': 'No locations available',
  'clickPlusToAddMore': 'Click the + icon to add more',
  // Rating and Reply related
  'reply': 'Reply',
  'writeAReply': 'Write a reply',
  'postReply': 'Post Reply',
  'replyPostedSuccessfully': 'Reply posted successfully',
  'failedToPostReply': 'Failed to post reply: {error}',
  'loadMore': 'Load more',
  'noItems': 'No items',
  'newRatings': 'New',
  'repliedRatings': 'Replied',
  'ratingsAndReplies': 'Ratings & Replies',
  'clickToManageImages': 'Click to manage images',
  'manage': 'Manage',
  'ongoing': 'Ongoing',
  'upcoming': 'Upcoming',
  'noVouchersAvailable': 'No vouchers available',
  'filter': 'Filter',
  'from': 'From',
  'to': 'To',
  'min': 'Min',
  'max': 'Max',
  'paid': 'Paid',
  'received': 'Received',
  'unpaid': 'Unpaid',
  'pendingLabel': 'Pending',
  'preparing': 'Preparing',
  'shipping': 'Shipping',
  'shipped': 'Shipped',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'warrantyStatusPending': 'Pending',
  'warrantyStatusProcessing': 'Processing',
  'warrantyStatusCompleted': 'Completed',
  'warrantyStatusDenied': 'Denied',
  'success': 'Success',
  'failure': 'Failure',
  'signInSuccess': 'Signed in successfully.',
  'signInFailed': 'Failed to sign in. Please try again.',
  'verificationLinkFailed':
      'Failed to send verification link. Please try again.',
  'sendingVerificationLink': 'Sending verification link...',
  'changePasswordFailed': 'Error changing password. Please try again.',
  'passwordsDoNotMatch': 'Passwords do not match.',
  'verificationEmailSent':
      'A verification email has been sent to your email address. Please verify your email to complete signing up.',
  'signUpFailed': 'Failed to sign up. Please try again.',
  'resetPasswordLinkSent':
      'A verification link has been sent to your email address. Please verify your email to reset your password.',
  'signOutFailed': 'Failed to sign out. Please try again.',
  'emailNotVerified': 'Email not verified. Please verify your email.',
  'invalidEmailOrPassword': 'Invalid email or password',
  'emailNotRegistered': 'This email is not registered in the system',
  'productAddedSuccess': 'Product added successfully.',
  'productAddFailed': 'Failed to add product. Please try again.',
  'productUpdatedSuccess': 'Product updated successfully.',
  'productUpdateFailed': 'Failed to update product. Please try again.',
  'unexpectedError': 'An unexpected error occurred. Please try again.',
  'chooseFromGallery': 'Choose from Gallery',
  'takePhoto': 'Take a Photo',
  'enterUrl': 'Enter URL',
  'enterImageUrl': 'Enter Image URL',
  'addProductImage': 'Add Product Image',
  'searchManufacturer': 'Search manufacturer...',
  'active': 'Active',
  'outOfStock': 'Out of Stock',
  'discontinued': 'Discontinued',
  'categorySpecifications': 'Specifications for',
  'ramBus': 'RAM Bus',
  'ramCapacity': 'RAM Capacity',
  'ramType': 'RAM Type',
  'cpuFamily': 'CPU Family',
  'cpuCore': 'CPU Core',
  'cpuThread': 'CPU Thread',
  'cpuClockSpeed': 'CPU Clock Speed',
  'psuWattage': 'PSU Wattage',
  'psuEfficiency': 'PSU Efficiency',
  'psuModular': 'PSU Modular',
  'gpuSeries': 'GPU Series',
  'gpuCapacity': 'GPU Capacity',
  'gpuBus': 'GPU Bus',
  'gpuClockSpeed': 'GPU Clock Speed',
  'formFactor': 'Form Factor',
  'series': 'Series',
  'compatibility': 'Compatibility',
  'driveType': 'Drive Type',
  'driveCapacity': 'Drive Capacity',
  'productName': 'Product Name',
  'sellingPrice': 'Selling Price',
  'discount': 'Discount',
  'stock': 'Stock',
  'additionalInformation': 'Additional Information',
  'releaseDate': 'Release Date',
  'manufacturer': 'Manufacturer',
  'drive': 'Drive',
  'mainboard': 'Mainboard',
  'findProducts': 'Find your item...',
  'noProductsFound': 'No products found',
  'releaseLatest': 'Release date: Latest',
  'releaseOldest': 'Release date: Oldest',
  'stockHighest': 'Stock: Highest',
  'stockLowest': 'Stock: Lowest',
  'salesHighest': 'Sale: Highest',
  'salesLowest': 'Sale: Lowest',
  'voucherAddedSuccess': 'Voucher added successfully.',
  'voucherAddFailed': 'Failed to add voucher. Please try again.',
  'voucherDeletedSuccess': 'Voucher deleted successfully.',
  'voucherDeleteFailed': 'Failed to delete voucher. Please try again.',
  'errorLoadingVouchers': 'Failed to load vouchers. Please try again.',
  'errorUpdatingVoucher': 'Failed to update voucher. Please try again.',
  'generateDescriptionButton': 'Generate description',
  'translateDescriptionButton': 'Translate description',
  'enDescription': 'English description',
  'viDescription': 'Vietnamese description',
  'descriptionGenerated': 'Description generated successfully.',
  'voucherEditSuccess': 'Voucher edited successfully.',
  'productDescription': 'Product description',
  'typeMessage': 'Type a message...',
  'manageProductImages': 'Manage Product Images',
  'uploadImage': 'Upload Image',
  'addUrl': 'Add URL',
  'primary': 'Primary',
  'pending': 'Pending',
  'newLabel': 'New',
  'pendingUpload': 'Pending upload',
  'closeWithoutSaving': 'Close without saving',
  'selectConversation': 'Select a conversation',
  'selectConversationToStart': 'Select a conversation to start chatting',
  'backToChatList': 'Back to chat list',
  'messages': 'Messages',
  'noMessages': 'No messages yet',
  'reactivate': 'Re-activate',
  'discontinue': 'Discontinue',
  'pleaseFillRequiredFields': 'Please fill in all required fields',
  'roleOwner': 'Owner',
  'roleManager': 'Manager',
  'roleEmployee': 'Employee',
  'appSettings': 'App Settings',
  'customizeAppPreferences': 'Customize your app preferences',
  'themeMode': 'Theme Mode',
  'switchBetweenLightAndDark': 'Switch between light and dark mode',
  'language': 'Language',
  'changeAppLanguage': 'Change the app language',
  'english': 'English',
  'vietnamese': 'Vietnamese',
  'signIn': 'Sign in',
  'signUp': 'Sign up',
  'forgotPassword': 'Forgot password?',
  'yourEmail': 'Your email',
  'password': 'Password',
  'authorizedByAdmin': 'Authorized by admin?',
  'passwordConfirmation': 'Password confirmation',
  'forgetPasswordTitle': 'Forget Password',
  'forgetPasswordDescription':
      'Don\'t worry! It happens. Please enter the email associated with your account.',
  'emailAddress': 'Email address',
  'enterYourEmailAddress': 'Enter your email address',
  'sendVerificationLink': 'Send Verification Link',
  'rememberYourPassword': 'Remember your password?',
  'ranOut': 'Ran out',
  'maximumDiscount': 'Maximum discount',
  'discountValue': 'Discount value',
  'voucherUpdateSuccess': 'Voucher updated successfully.',
  'voucherUpdateFailed': 'Failed to update voucher. Please try again.',
  'giftVouchers': 'Gift Vouchers',
  'confirmation': 'Confirmation',
  'confirmGiftVoucher':
      'Gift this voucher to customer? This action cannot be undone.',
  'giveVoucherSuccess': 'Gift voucher successfully.',
  'giveVoucherFailed': 'Failed to gift voucher. Please try again.',
  'starts': 'Starts',
  'expires': 'Expires',
  'expired': 'Expired',
  'addressAddedSuccess': 'Address added successfully.',
  'addressAddFailed': 'Failed to add address. Please try again.',
  'addressUpdatedSuccess': 'Address updated successfully.',
  'addressUpdateFailed': 'Failed to update address. Please try again.',
  'editAddress': 'Edit Address',
  'saveAddress': 'Save Address',
  'chooseYear': 'Choose Year',
  'chooseMonth': 'Choose Month',
  'selectMonth': 'Select Month',
  'yearMonthly': 'Year (monthly)',
  'monthDaily': 'Month (daily)',
  'voucherUpdatedSuccess': 'Voucher updated successfully.',
  'warrantyInvoiceUpdatedSuccess': 'Warranty invoice updated successfully.',
  'editProduct': 'Edit Product',
  // Business Report
  'businessReport': 'Business Report',
  'selectReportPeriod': 'Select Report Period',
  'period': 'Period',
  'today': 'Today',
  'thisWeek': 'This Week',
  'thisMonth': 'This Month',
  'thisYear': 'This Year',
  'custom': 'Custom',
  'startDate': 'Start Date',
  'endDate': 'End Date',
  'selectStartDate': 'Select start date',
  'selectEndDate': 'Select end date',
  'selectedPeriod': 'Selected Period',
  'createReport': 'Create Report',
  'generatingReport': 'Generating report...',
  'thisMayTakeFewMoments': 'This may take a few moments',
  'reportGeneratedSuccess':
      'Business report generated and downloaded successfully',
  'errorGeneratingReport': 'Error generating business report',
  'pleaseSelectValidDateRange': 'Please select a valid date range',
  'reportPeriod': 'Report Period',
  'executiveSummary': 'Executive Summary',
  'totalRevenue': 'Total Revenue',
  'totalCosts': 'Total Costs',
  'grossProfit': 'Gross Profit',
  'profitMargin': 'Profit Margin',
  'totalOrders': 'Total Orders',
  'averageOrderValue': 'Average Order Value',
  'financialOverview': 'Financial Overview',
  'revenueMetrics': 'Revenue Metrics',
  'costMetrics': 'Cost Metrics',
  'salesAnalysis': 'Sales Analysis',
  'totalProducts': 'Total Products',
  'totalCustomers': 'Total Customers',
  'totalSalesInvoices': 'Total Sales Invoices',
  'totalIncomingInvoices': 'Total Incoming Invoices',
  'topProducts': 'Top Products',
  'productId': 'Product ID',
  'quantitySold': 'Quantity Sold',
  'salesByCategory': 'Sales by Category',
  'revenueBreakdown': 'Revenue Breakdown',
  'revenueByCategory': 'Revenue by Category',
  'monthlyRevenue': 'Monthly Revenue',
  'costBreakdown': 'Cost Breakdown',
  'costOfGoodsSold': 'Cost of Goods Sold (COGS)',
  'operatingExpenses': 'Operating Expenses',
  'customerInsights': 'Customer Insights',
  'newCustomers': 'New Customers',
  'returningCustomers': 'Returning Customers',
  'customerRetentionRate': 'Customer Retention Rate',
  'topCustomersBySpending': 'Top Customers by Spending',
  'orders': 'Orders',
  'totalSpending': 'Total Spending',
  'bestSellingProducts': 'Best-Selling Products',
  'topProductsByQuantity': 'Top Products by Quantity Sold',
  'inventoryInsights': 'Inventory Insights',
  'totalStockValue': 'Total Stock Value',
  'lowStockItems': 'Low Stock Items',
  'currentStock': 'Current Stock',
  'inventoryTurnoverRate': 'Inventory Turnover Rate',
  'salesTrends': 'Sales Trends',
  'monthlySalesTrend': 'Monthly Sales Trend',
  'month': 'Month',
  'costs': 'Costs',
  'profit': 'Profit',
  'businessKPIs': 'Business KPIs',
  'averageItemsPerOrder': 'Average Items per Order',
  'totalItemsSold': 'Total Items Sold',
  'conclusionInsights': 'Conclusion & Insights',
  'noSpecificInsights': 'No specific insights available for this period.',
  'strongProfitMargin':
      '[OK] Strong profit margin indicates healthy business operations',
  'lowProfitMargin':
      '[WARNING] Low profit margin - consider reviewing costs and pricing strategy',
  'goodCustomerRetention':
      '[OK] Good customer retention rate shows strong customer loyalty',
  'improveCustomerRetention':
      '[WARNING] Customer retention could be improved with better engagement strategies',
  'lowStockAlert':
      '[WARNING] {count} items are low in stock - consider restocking',
  'consistentRevenue':
      '[OK] Business is generating consistent revenue with {orders} orders',
  'reportGeneratedBy': 'Report Generated By',
  'generatedOn': 'Generated On',
  'cpuSeries': 'CPU Series',
  'cpuSocket': 'CPU Socket',
  'cpuBaseClock': 'CPU Base Clock Speed (GHz)',
  'cpuTurboClock': 'CPU Turbo Clock Speed (GHz)',
  'cpuTdp': 'CPU TDP (W)',
  'numberOfCpuCores': 'Number of CPU Cores',
  'numberOfCpuThreads': 'Number of CPU Threads',
  'gpuVersion': 'GPU Version',
  'gpuMemory': 'GPU Memory (GB)',
  'gpuTdp': 'GPU TDP (W)',
  'gpuBoostClock': 'GPU Boost Clock (GHz)',
  'connectorType': 'Connector Type',
  'addConnector': 'Add Connector',
  'addIoPort': 'Add IO Port',
  'addPcieSlot': 'Add PCIe Slot',
  'driveGeneration': 'Drive Generation',
  'chipsetCode': 'Chipset Code',
  'mainboardFormFactor': 'Mainboard Form Factor',
  'supportedRamType': 'Supported RAM Type',
  'numberOfSataPorts': 'Number of SATA Ports',
  'numberOfM2Slots': 'Number of M.2 Slots',
  'physicalSize': 'Physical Size',
  'electricalSpeed': 'Electrical Speed',
  'generation': 'Generation',
  'interfaceType': 'Interface Type',
  'driveFormFactor': 'Drive Form Factor',
  'capacityPerStick': 'Capacity per Stick (GB)',
  'kitStickCount': 'Kit Stick Count',
  'clLatency': 'CL Latency',
  'maxWattage': 'Max Wattage (W)',
  'psuModularity': 'PSU Modularity',
  'port': 'Port',
  'thisFieldIsRequired': 'This field is required',
  'ramBusSpeed': 'RAM Bus Speed (MHz)',
  'maximumSingleRamCapacity': 'Maximum Single RAM Capacity (GB)',
  'capacity': 'Capacity (GB)',
  'readSpeed': 'Read Speed (MB/s)',
  'writeSpeed': 'Write Speed (MB/s)',
  'select': 'Select',
  'year': 'Year',
  'generateBusinessReport': 'Generate Business Report',
  'noData': 'No Data',
  'productCategoryDistribution': 'Product Category Distribution',
  'ratingsAndReviews': 'Ratings & Reviews',
  'reviews': 'reviews',
  'noRatingsYet': 'No ratings yet',
  'showMore': 'Show more',
  'version': 'Version',
  'memory': 'Memory',
  'clockSpeed': 'Clock Speed',
  'tdp': 'TDP',
  'ioPorts': 'I/O Ports',
  'cores': 'Cores',
  'threads': 'Threads',
  'baseClock': 'Base Clock',
  'turboClock': 'Turbo Clock',
  'socket': 'Socket',
  'chipset': 'Chipset',
  'ramSpec': 'RAM Spec',
  'storage': 'Storage',
  'pcieSlots': 'PCIe Slots',
  'connectors': 'Connectors',
  'efficiencyRating': 'Efficiency Rating',
  'modularity': 'Modularity',
  'bus': 'Bus',
  'type': 'Type',
  // Voucher distribution types
  'distributionPublic': 'Public',
  'distributionRewards': 'Rewards',
  'distributionStaffIssued': 'Staff-Issued',
  'rewardsFor': 'Rewards for {points}',
  'refresh': 'Refresh',
  'anonymous': 'Anonymous',
  'numberOfRamSlots': 'Number of RAM slots',
  'tryAgain': 'Please try again later',

};
