const Map<String, String> vi = {
  'appTitle': 'GizmoGlobe',
  'welcomeBack': 'Chào mừng trở lại,',
  'overview': 'Tổng quan',
  'products': 'Sản phẩm',
  'customers': 'Khách hàng',
  'revenue': 'Doanh thu',
  'avgIncome': 'Thu nhập trung bình',
  'monthlySales': 'Doanh số hàng tháng',
  'last12Months': '12 tháng qua',
  'last3Months': '3 tháng qua',
  'newIncomingInvoice': 'Tạo hóa đơn nhập mới',
  'selectManufacturer': 'Chọn nhà sản xuất',
  'addProduct': 'Thêm sản phẩm',
  'invoiceDetails': 'Hóa đơn',
  'importPrice': 'Giá nhập',
  'quantity': 'Số lượng',
  'totalPrice': 'Tổng giá: ',
  'paymentStatus': 'Trạng thái thanh toán',
  'createInvoice': 'Tạo hóa đơn',
  'cancel': 'Hủy',
  'add': 'Thêm',
  'editProductDetail': 'Chỉnh sửa chi tiết sản phẩm',
  'update': 'Cập nhật',
  'createInvoiceSuccess': 'Tạo hóa đơn thành công.',
  'editInvoiceSuccess': 'Chỉnh sửa hóa đơn thành công.',
  'createIncomingInvoiceSuccess': 'Tạo hóa đơn nhập thành công.',
  'updateIncomingInvoiceSuccess': 'Cập nhật hóa đơn nhập thành công.',
  'searchIncomingInvoices': 'Tìm hóa đơn nhập...',
  'noIncomingInvoicesFound': 'Không tìm thấy hóa đơn nhập',
  'view': 'Xem',
  'editPayment': 'Chỉnh sửa thanh toán',
  'onlyUnpaidCanBeMarkedPaid':
      'Chỉ hóa đơn chưa thanh toán mới có thể đánh dấu là đã thanh toán',
  'markAsPaidQuestion': 'Đánh dấu hóa đơn này là đã thanh toán?',
  'confirm': 'Xác nhận',
  'sortBy': 'Sắp xếp theo ',
  'dateNewestFirst': 'Ngày (Mới nhất trước)',
  'dateOldestFirst': 'Ngày (Cũ nhất trước)',
  'priceHighestFirst': 'Giá (Cao nhất trước)',
  'priceLowestFirst': 'Giá (Thấp nhất trước)',
  'errorOccurred': 'Có lỗi xảy ra',
  'newInvoice': 'Hóa đơn mới',
  'customerInformation': 'Thông tin khách hàng',
  'selectCustomer': 'Chọn khách hàng',
  'customer': 'Khách hàng',
  'pleaseSelectCustomer': 'Vui lòng chọn khách hàng',
  'address': 'Địa chỉ',
  'pleaseSelectAddress': 'Vui lòng chọn địa chỉ',
  'salesStatus': 'Trạng thái bán hàng',
  'totalAmount': 'Tổng số tiền',
  'noProductsAddedYet': 'Chưa thêm sản phẩm nào',
  'price': 'Giá',
  'availableStock': 'Hàng tồn kho',
  'pleaseSelectCustomerFirst': 'Vui lòng chọn khách hàng trước',
  'searchSalesInvoices': 'Tìm hóa đơn bán hàng...',
  'noSalesInvoicesFound': 'Không tìm thấy hóa đơn bán hàng',
  'warrantyReceipt': 'Biên lai bảo hành #{id}',
  'warrantyInformation': 'Thông tin bảo hành',
  'status': 'Trạng thái',
  'reasonForWarranty': 'Lý do bảo hành',
  'productsUnderWarranty': 'Sản phẩm được bảo hành',
  'unknownCategory': 'Không xác định',
  'unknown': 'Không xác định',
  'updateWarrantyStatus': 'Cập nhật trạng thái bảo hành',
  'confirmStatusUpdate': 'Xác nhận cập nhật trạng thái',
  'areYouSureChangeStatus':
      'Bạn có chắc chắn muốn thay đổi trạng thái thành {status}?',
  'save': 'Lưu',
  'updateStatus': 'Cập nhật trạng thái',
  'noSalesInvoicesAvailable': 'Không có hóa đơn bán hàng',
  'noEligibleSalesInvoices':
      'Khách hàng này không có hóa đơn bán hàng nào hợp lệ để yêu cầu bảo hành.',
  'pleaseSelectSalesInvoice': 'Vui lòng chọn hóa đơn bán hàng',
  'reasonForWarrantyLabel': 'Lý do bảo hành',
  'selectProductsForWarranty': 'Chọn sản phẩm để bảo hành',
  'warrantyInvoiceCreated': 'Tạo hóa đơn bảo hành thành công',
  'errorCreatingWarrantyInvoice': 'Lỗi tạo hóa đơn bảo hành: {error}',
  'product': 'Sản phẩm',
  'selectProduct': 'Chọn sản phẩm',
  'pleaseSelectProduct': 'Vui lòng chọn sản phẩm',
  'quantityGreaterThanZero': 'Số lượng phải lớn hơn 0',
  'notEnoughStock': 'Không đủ hàng tồn',
  'noAddressFound': 'Không tìm thấy địa chỉ nào',
  'date': 'Ngày',
  'subtotal': 'Tổng phụ',
  'editInvoice': 'Chỉnh sửa hóa đơn',
  'changeAddress': 'Thay đổi địa chỉ',
  'unknownProduct': 'Sản phẩm không xác định',
  'errorWithMessage': 'Lỗi: {error}',
  'errorLoadingInvoiceDetails': 'Lỗi tải chi tiết hóa đơn: {error}',
  'salesInvoice': 'Hóa đơn bán hàng',
  'loading': 'Đang tải...',
  'category': 'Danh mục',
  'enterAddress': 'Nhập địa chỉ',
  'findWarrantyInvoices': 'Tìm hóa đơn bảo hành...',
  'noWarrantyInvoicesFound': 'Không tìm thấy hóa đơn bảo hành',
  'markAsCompleted': 'Đánh dấu là đã hoàn thành',
  'errorLoadingWarrantyInvoiceDetails':
      'Lỗi khi tải chi tiết hóa đơn bảo hành: {error}',
  'sales': 'Bán hàng',
  'incoming': 'Nhập hàng',
  'warranty': 'Bảo hành',
  'hello': 'Xin chào!',
  'contactUs': 'Liên hệ:',
  'logOut': 'Đăng xuất',
  'home': 'Trang chủ',
  'invoice': 'Hóa đơn',
  'stakeholder': 'Đối tác',
  'voucher': 'Phiếu giảm giá',
  'profile': 'Hồ sơ',
  'addNewAddress': 'Thêm địa chỉ mới',
  'receiverName': 'Tên người nhận',
  'enterReceiverName': 'Nhập tên người nhận',
  'receiverPhone': 'Số điện thoại người nhận',
  'enterPhoneNumber': 'Nhập số điện thoại',
  'location': 'Địa chỉ',
  'streetAddress': 'Địa chỉ cụ thể',
  'streetNameBuildingHouseNo': 'Tên đường, tòa nhà, số nhà',
  'addAddress': 'Thêm địa chỉ',
  'customerDetail': 'Chi tiết khách hàng',
  'edit': 'Chỉnh sửa',
  'name': 'Tên',
  'email': 'Email',
  'phone': 'Số điện thoại',
  'addresses': 'Địa chỉ',
  'pleaseFillInAllRequiredFields': 'Vui lòng điền tất cả các trường bắt buộc',
  'discardChanges': 'Hủy bỏ thay đổi?',
  'unsavedChangesDiscard':
      'Bạn có thay đổi chưa lưu. Bạn có muốn hủy bỏ chúng?',
  'discard': 'BỎ QUA',
  'editCustomer': 'Chỉnh sửa khách hàng',
  'fullName': 'Họ và tên',
  'nameIsRequired': 'Tên là bắt buộc',
  'nameMin2Chars': 'Tên phải có ít nhất 2 ký tự',
  'phoneNumber': 'Số điện thoại',
  'phoneNumberIsRequired': 'Số điện thoại là bắt buộc',
  'pleaseEnterValidPhoneNumber': 'Vui lòng nhập số điện thoại hợp lệ',
  'addNewCustomer': 'Thêm khách hàng mới',
  'addCustomer': 'Thêm khách hàng',
  'pleaseFillInAllFields': 'Vui lòng điền tất cả các trường',
  'customerAddedSuccessfully': 'Khách hàng đã được thêm thành công',
  'findCustomers': 'Tìm kiếm khách hàng...',
  'noMatchingCustomersFound': 'Không tìm thấy khách hàng nào phù hợp',
  'employeeDetail': 'Chi tiết nhân viên',
  'employeeInformation': 'Thông tin nhân viên',
  'role': 'Chức vụ',
  'delete': 'Xóa',
  'deleteEmployee': 'Xóa nhân viên',
  'areYouSureDeleteEmployee': 'Bạn có chắc chắn muốn xóa nhân viên này?',
  'editEmployee': 'Chỉnh sửa nhân viên',
  'pleaseEnterName': 'Vui lòng nhập tên',
  'pleaseEnterPhoneNumber': 'Vui lòng nhập số điện thoại',
  'pleaseSelectRole': 'Vui lòng chọn vai trò',
  'addNewEmployee': 'Thêm nhân viên mới',
  'pleaseEnterEmail': 'Vui lòng nhập địa chỉ email',
  'filterByRole': 'Lọc theo vai trò',
  'clearFilter': 'Xóa bộ lọc',
  'findEmployees': 'Tìm kiếm nhân viên...',
  'noEmployeesFound': 'Không tìm thấy nhân viên nào',
  'employeeAddedSuccessfully': 'Nhân viên đã được thêm thành công',
  'manufacturerDetail': 'Chi tiết nhà cung cấp',
  'deactivate': 'Vô hiệu hóa',
  'activate': 'Kích hoạt',
  'deactivateManufacturer': 'Vô hiệu hóa nhà cung cấp',
  'activateManufacturer': 'Kích hoạt nhà cung cấp',
  'deactivateManufacturerConfirm':
      'Bạn có chắc chắn muốn vô hiệu hóa nhà cung cấp này?',
  'activateManufacturerConfirm':
      'Bạn có chắc chắn muốn kích hoạt nhà cung cấp này?',
  'inactive': 'Vô hiệu hóa',
  'manufacturerInformation': 'Thông tin nhà cung cấp',
  'manufacturerName': 'Tên nhà cung cấp',
  'editManufacturer': 'Chỉnh sửa nhà sản xuất',
  'addNewManufacturer': 'Thêm nhà sản xuất mới',
  'addManufacturer': 'Thêm nhà sản xuất',
  'findManufacturers': 'Tìm kiếm nhà sản xuất...',
  'noMatchingManufacturersFound': 'Không tìm thấy nhà sản xuất nào phù hợp',
  'manufacturerAddedSuccessfully': 'Thêm nhà sản xuất thành công',
  'deactivateManufacturerConfirmName':
      'Bạn có chắc chắn muốn vô hiệu hóa {name}?',
  'activateManufacturerConfirmName': 'Bạn có chắc chắn muốn kích hoạt {name}?',
  'employees': 'Nhân viên',
  'vendors': 'Nhà cung cấp',
  'appAvatar': 'Biểu tượng ứng dụng',
  'createNewAccount': 'Tạo tài khoản mới',
  'alreadyHaveAccount': 'Đã có tài khoản?',
  'informationTitle': 'Thông tin',
  'aboutGizmoGlobe': 'Về GizmoGlobe',
  'aboutUsTitle': 'Về chúng tôi',
  'aboutUsContent':
      'GizmoGlobe là giải pháp phần cứng máy tính đáng tin cậy của bạn.',
  'ourMissionTitle': 'Sứ mệnh của chúng tôi',
  'ourMissionContent':
      'Cung cấp dịch vụ xuất sắc và sản phẩm chất lượng cho bạn, khách hàng thân yêu của chúng tôi.',
  'contactInformationTitle': 'Thông tin liên hệ',
  'contactInformationContent': 'Địa chỉ: UIT',
  'businessHoursTitle': 'Giờ làm việc',
  'businessHoursContent':
      'Thứ Hai - Thứ Sáu: 9:00 sáng - 6:00 chiều\nThứ Bảy: 10:00 sáng - 4:00 chiều\nChủ Nhật: Đóng cửa',
  'supportTitle': 'Hỗ trợ',
  'supportMembers': 'Thành viên nhóm',
  'supportRoleDeveloper': 'Lập trình viên',
  'supportStudentId': 'Mã số sinh viên: {id}',
  'supportRole': 'Vai trò: {role}',
  'supportEmail': 'Email: {email}',
  'accountSettings': 'Cài đặt tài khoản',
  'editProfile': 'Chỉnh sửa hồ sơ',
  'updatePersonalInfo': 'Cập nhật thông tin cá nhân',
  'changePassword': 'Đổi mật khẩu',
  'manageAccountSecurity': 'Quản lý bảo mật tài khoản của bạn',
  'signOut': 'Đăng xuất',
  'username': 'Tên người dùng',
  'saveChanges': 'Lưu thay đổi',
  'updateProfileSuccess': 'Cập nhật hồ sơ thành công',
  'passwordResetEmailWillBeSent':
      'Email đặt lại mật khẩu sẽ được gửi đến địa chỉ email của bạn',
  'passwordResetEmailSentSuccess':
      'Email đặt lại mật khẩu đã được gửi thành công',
  'sendPasswordResetEmail': 'Gửi email đặt lại mật khẩu',
  'noUserSignedIn': 'Không có người dùng đăng nhập',
  'addVoucher': 'Thêm voucher',
  'basicInformation': 'Thông tin cơ bản',
  'voucherName': 'Tên voucher',
  'minimumPurchase': 'Giá trị tối thiểu',
  'startTime': 'Thời gian bắt đầu',
  'maxUsagePerPerson': 'Số lần sử dụng tối đa mỗi người',
  'description': 'Mô tả',
  'voucherSettings': 'Cài đặt voucher',
  'discountType': 'Loại giảm giá',
  'fixedAmount': 'Số tiền cố định',
  'percentage': 'Phần trăm',
  'maximumDiscountValue': 'Giá trị giảm giá tối đa',
  'usageLimit': 'Giới hạn sử dụng',
  'unlimited': 'Không giới hạn',
  'limited': 'Có giới hạn',
  'maximumUsage': 'Số lần sử dụng tối đa',
  'usageLeft': 'Số lần còn lại',
  'timeLimit': 'Giới hạn thời gian',
  'noEndTime': 'Không có thời gian kết thúc',
  'hasEndTime': 'Có thời gian kết thúc',
  'endTime': 'Thời gian kết thúc',
  'voucherWillNotExpire': 'Voucher này sẽ không hết hạn',
  'visibility': 'Hiển thị',
  'hidden': 'Ẩn',
  'visible': 'Hiển thị',
  'disabled': 'Vô hiệu hóa',
  'enabled': 'Kích hoạt',
  'selectField': 'Chọn {field}',
  'enterField': 'Nhập {field}',
  'all': 'Tất cả',
  'ongoing': 'Khả dụng',
  'upcoming': 'Sắp đến',
  'noVouchersAvailable': 'Không có phiếu giảm giá nào khả dụng',
  'filter': 'Lọc',
  'from': 'Từ',
  'to': 'Đến',
  'min': 'Tối thiểu',
  'max': 'Tối đa',
  'paid': 'Đã thanh toán',
  'unpaid': 'Chưa thanh toán',
  'pending': 'Chờ xử lý',
  'preparing': 'Đang chuẩn bị',
  'shipping': 'Đang giao',
  'shipped': 'Đã giao',
  'reveiced': 'Đã nhận',
  'completed': 'Đã hoàn thành',
  'cancelled': 'Đã hủy',
  'warrantyStatusPending': 'Chờ xử lý',
  'warrantyStatusProcessing': 'Đang xử lý',
  'warrantyStatusCompleted': 'Đã hoàn thành',
  'warrantyStatusDenied': 'Từ chối',
  'success': 'Thành công',
  'failure': 'Thất bại',
  'signInSuccess': 'Đăng nhập thành công.',
  'signInFailed': 'Đăng nhập thất bại. Vui lòng thử lại.',
  'sendingVerificationLink': 'Gửi liên kết xác minh...',
  'verificationLinkFailed': 'Gửi liên kết xác minh thất bại. Vui lòng thử lại.',
  'changePasswordFailed': 'Lỗi thay đổi mật khẩu. Vui lòng thử lại.',
  'passwordsDoNotMatch': 'Mật khẩu không khớp.',
  'verificationEmailSent':
      'Một email xác minh đã được gửi đến địa chỉ email của bạn. Vui lòng xác minh email của bạn để hoàn tất việc đăng ký.',
  'signUpFailed': 'Đăng ký thất bại. Vui lòng thử lại.',
  'resetPasswordLinkSent':
      'Một liên kết xác minh đã được gửi đến địa chỉ email của bạn. Vui lòng xác minh email của bạn để đặt lại mật khẩu.',
  'signOutFailed': 'Đăng xuất thất bại. Vui lòng thử lại.',
  'emailNotVerified':
      'Email chưa được xác minh. Vui lòng xác minh email của bạn.',
  'invalidEmailOrPassword': 'Email hoặc mật khẩu không hợp lệ',
  'emailNotRegistered': 'Email này không được đăng ký trong hệ thống',
  'productAddedSuccess': 'Sản phẩm đã được thêm thành công.',
  'productAddFailed': 'Không thể thêm sản phẩm. Vui lòng thử lại.',
  'productUpdatedSuccess': 'Sản phẩm đã được cập nhật thành công.',
  'productUpdateFailed': 'Không thể cập nhật sản phẩm. Vui lòng thử lại.',
  'unexpectedError': 'Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.',
  'chooseFromGallery': 'Chọn từ thư viện',
  'takePhoto': 'Chụp ảnh',
  'enterUrl': 'Nhập URL',
  'enterImageUrl': 'Nhập URL hình ảnh',
  'addProductImage': 'Thêm hình sản phẩm',
  'searchManufacturer': 'Tìm kiếm nhà sản xuất...',
  'active': 'Đang hoạt động',
  'outOfStock': 'Hết hàng',
  'discontinued': 'Ngừng kinh doanh',
  'categorySpecifications': 'Thông số cho',
  'ramBus': 'Bus RAM',
  'ramCapacity': 'Dung lượng RAM',
  'ramType': 'Loại RAM',
  'cpuFamily': 'Dòng CPU',
  'cpuCore': 'Số nhân CPU',
  'cpuThread': 'Số luồng CPU',
  'cpuClockSpeed': 'Tốc độ CPU',
  'psuWattage': 'Công suất PSU',
  'psuEfficiency': 'Hiệu suất PSU',
  'psuModular': 'PSU Modular',
  'gpuSeries': 'Dòng GPU',
  'gpuCapacity': 'Dung lượng GPU',
  'gpuBus': 'Bus GPU',
  'gpuClockSpeed': 'Tốc độ GPU',
  'formFactor': 'Kiểu dáng',
  'series': 'Dòng sản phẩm',
  'compatibility': 'Tương thích',
  'driveType': 'Loại ổ đĩa',
  'driveCapacity': 'Dung lượng ổ đĩa',
  'productName': 'Tên sản phẩm',
  'sellingPrice': 'Giá bán',
  'discount': 'Giảm giá',
  'stock': 'Tồn kho',
  'additionalInformation': 'Thông tin bổ sung',
  'releaseDate': 'Ngày phát hành',
  'manufacturer': 'Nhà sản xuất',
  'drive': 'Ổ cứng',
  'mainboard': 'Bo mạch chủ',
  'findProducts': 'Tìm kiếm sản phẩm...',
  'noProductsFound': 'Không tìm thấy sản phẩm nào',
  'releaseLatest': 'Ngày phát hành: Mới nhất',
  'releaseOldest': 'Ngày phát hành: Cũ nhất',
  'stockHighest': 'Hàng tồn kho: Cao nhất',
  'stockLowest': 'Hàng tồn kho: Thấp nhất',
  'salesHighest': 'Số lượng bán: Cao nhất',
  'salesLowest': 'Số lượng bán: Thấp nhất',
  'voucherAddedSuccess': 'Thêm phiếu giảm giá thành công.',
  'voucherAddFailed': 'Thêm phiếu giảm giá thất bại. Vui lòng thử lại.',
  'voucherDeletedSuccess': 'Xóa phiếu giảm giá thành công.',
  'voucherDeleteFailed': 'Xóa phiếu giảm giá thất bại. Vui lòng thử lại.',
  'errorLoadingVouchers': 'Không thể tải voucher. Vui lòng thử lại.',
  'errorUpdatingVoucher': 'Cập nhật phiếu giảm giá thất bại. Vui lòng thử lại.',
  'generateDescriptionButton': 'Tạo mô tả',
  'translateDescriptionButton': 'Dịch mô tả',
  'enDescription': 'Mô tả tiếng Anh',
  'viDescription': 'Mô tả tiếng Việt',
  'descriptionGenerated': 'Mô tả được tạo thành công.',
  'voucherEditSuccess': 'Sửa phiếu giảm giá thành công.',
  'productDescription': 'Mô tả sản phẩm',
  'typeMessage': 'Nhập tin nhắn...',
  'selectConversation': 'Chọn cuộc trò chuyện',
  'messages': 'Tin nhắn',
  'noMessages': 'Không có tin nhắn',
  'reactivate': 'Kích hoạt lại',
  'discontinue': 'Ngừng kinh doanh',
  'pleaseFillRequiredFields': 'Vui lòng điền đầy đủ các trường bắt buộc',
  'roleOwner': 'Chủ sở hữu',
  'roleManager': 'Quản lý',
  'roleEmployee': 'Nhân viên',
  'appSettings': 'Cài đặt ứng dụng',
  'customizeAppPreferences': 'Tùy chỉnh cài đặt ứng dụng của bạn',
  'themeMode': 'Chế độ giao diện',
  'switchBetweenLightAndDark': 'Chuyển đổi giữa chế độ sáng và tối',
  'language': 'Ngôn ngữ',
  'changeAppLanguage': 'Thay đổi ngôn ngữ ứng dụng',
  'english': 'Tiếng Anh',
  'vietnamese': 'Tiếng Việt',
  'signIn': 'Đăng nhập',
  'signUp': 'Đăng ký',
  'forgotPassword': 'Quên mật khẩu?',
  'yourEmail': 'Email của bạn',
  'password': 'Mật khẩu',
  'authorizedByAdmin': 'Được phê duyệt bởi admin?',
  'passwordConfirmation': 'Xác nhận mật khẩu',
  'forgetPasswordTitle': 'Quên mật khẩu',
  'forgetPasswordDescription':
      'Đừng lo lắng! Điều này xảy ra. Vui lòng nhập email liên kết với tài khoản của bạn.',
  'emailAddress': 'Địa chỉ email',
  'enterYourEmailAddress': 'Nhập địa chỉ email của bạn',
  'sendVerificationLink': 'Gửi liên kết xác minh',
  'rememberYourPassword': 'Nhớ mật khẩu?',
  'ranOut': 'Đã hết',
  'maximumDiscount': 'Giảm giá tối đa',
  'discountValue': 'Giá trị giảm giá',
  'voucherUpdateSuccess': 'Cập nhật phiếu giảm giá thành công.',
  'voucherUpdateFailed': 'Cập nhật phiếu giảm giá thất bại. Vui lòng thử lại.',
  'giftVouchers': 'Tặng phiếu giảm giá',
  'confirmation': 'Xác nhận',
  'confirmGiftVoucher':
      'Tặng phiếu giảm giá này cho khách hàng? Hành động này sẽ không thể hoàn tác.',
  'giveVoucherSuccess': 'Tặng phiếu giảm giá thành công.',
  'giveVoucherFailed': 'Tặng phiếu giảm giá thất bại. Vui lòng thử lại.',
  'starts': 'Bắt đầu',
  'expires': 'Kết thúc',
  'expired': 'Đã hết hạn',
  'addressAddedSuccess': 'Địa chỉ đã được thêm thành công.',
  'addressAddFailed': 'Không thể thêm địa chỉ. Vui lòng thử lại.',
  'addressUpdatedSuccess': 'Địa chỉ đã được cập nhật thành công.',
  'addressUpdateFailed': 'Không thể cập nhật địa chỉ. Vui lòng thử lại.',
  'editAddress': 'Chỉnh sửa địa chỉ',
  'saveAddress': 'Lưu địa chỉ',
  'chooseYear': 'Chọn năm',
  'chooseMonth': 'Chọn tháng',
  'selectMonth': 'Chọn tháng',
  'yearMonthly': 'Năm (tháng)',
  'monthDaily': 'Tháng (ngày)',
  'voucherUpdatedSuccess': 'Phiếu giảm giá đã được cập nhật thành công.',
  'warrantyInvoiceUpdatedSuccess':
      'Hóa đơn bảo hành đã được cập nhật thành công.',
  'editProduct': 'Chỉnh sửa sản phẩm',
  // Business Report
  'businessReport': 'Báo cáo Kinh doanh',
  'selectReportPeriod': 'Chọn Khoảng thời gian Báo cáo',
  'period': 'Khoảng thời gian',
  'today': 'Hôm nay',
  'thisWeek': 'Tuần này',
  'thisMonth': 'Tháng này',
  'thisYear': 'Năm này',
  'custom': 'Tùy chỉnh',
  'startDate': 'Ngày bắt đầu',
  'endDate': 'Ngày kết thúc',
  'selectStartDate': 'Chọn ngày bắt đầu',
  'selectEndDate': 'Chọn ngày kết thúc',
  'selectedPeriod': 'Khoảng thời gian đã chọn',
  'createReport': 'Tạo Báo cáo',
  'generatingReport': 'Đang tạo báo cáo...',
  'thisMayTakeFewMoments': 'Quá trình này có thể mất vài phút',
  'reportGeneratedSuccess':
      'Báo cáo kinh doanh đã được tạo và tải xuống thành công',
  'errorGeneratingReport': 'Lỗi khi tạo báo cáo kinh doanh',
  'pleaseSelectValidDateRange': 'Vui lòng chọn khoảng thời gian hợp lệ',
  'reportPeriod': 'Khoảng thời gian Báo cáo',
  'executiveSummary': 'Tóm tắt Điều hành',
  'totalRevenue': 'Tổng Doanh thu',
  'totalCosts': 'Tổng Chi phí',
  'grossProfit': 'Lợi nhuận Gộp',
  'profitMargin': 'Tỷ suất Lợi nhuận',
  'totalOrders': 'Tổng số Đơn hàng',
  'averageOrderValue': 'Giá trị Đơn hàng Trung bình',
  'financialOverview': 'Tổng quan Tài chính',
  'revenueMetrics': 'Chỉ số Doanh thu',
  'costMetrics': 'Chỉ số Chi phí',
  'salesAnalysis': 'Phân tích Bán hàng',
  'totalProducts': 'Tổng số Sản phẩm',
  'totalCustomers': 'Tổng số Khách hàng',
  'totalSalesInvoices': 'Tổng số Hóa đơn Bán hàng',
  'totalIncomingInvoices': 'Tổng số Hóa đơn Nhập hàng',
  'topProducts': 'Sản phẩm Hàng đầu',
  'productId': 'Mã Sản phẩm',
  'quantitySold': 'Số lượng Bán ra',
  'salesByCategory': 'Bán hàng theo Danh mục',
  'revenueBreakdown': 'Phân tích Doanh thu',
  'revenueByCategory': 'Doanh thu theo Danh mục',
  'monthlyRevenue': 'Doanh thu Hàng tháng',
  'costBreakdown': 'Phân tích Chi phí',
  'costOfGoodsSold': 'Giá vốn Hàng bán (COGS)',
  'operatingExpenses': 'Chi phí Hoạt động',
  'customerInsights': 'Thông tin Khách hàng',
  'newCustomers': 'Khách hàng Mới',
  'returningCustomers': 'Khách hàng Quay lại',
  'customerRetentionRate': 'Tỷ lệ Giữ chân Khách hàng',
  'topCustomersBySpending': 'Khách hàng Hàng đầu theo Chi tiêu',
  'orders': 'Đơn hàng',
  'totalSpending': 'Tổng Chi tiêu',
  'bestSellingProducts': 'Sản phẩm Bán chạy',
  'topProductsByQuantity': 'Sản phẩm Hàng đầu theo Số lượng',
  'inventoryInsights': 'Thông tin Tồn kho',
  'totalStockValue': 'Tổng Giá trị Tồn kho',
  'lowStockItems': 'Sản phẩm Tồn kho Thấp',
  'currentStock': 'Tồn kho Hiện tại',
  'inventoryTurnoverRate': 'Tỷ lệ Vòng quay Tồn kho',
  'salesTrends': 'Xu hướng Bán hàng',
  'monthlySalesTrend': 'Xu hướng Bán hàng Hàng tháng',
  'month': 'Tháng',
  'costs': 'Chi phí',
  'profit': 'Lợi nhuận',
  'businessKPIs': 'Chỉ số KPI Kinh doanh',
  'averageItemsPerOrder': 'Số lượng Sản phẩm Trung bình mỗi Đơn',
  'totalItemsSold': 'Tổng số Sản phẩm Đã bán',
  'conclusionInsights': 'Kết luận & Nhận định',
  'noSpecificInsights': 'Không có nhận định cụ thể cho khoảng thời gian này.',
  'strongProfitMargin':
      '[OK] Tỷ suất lợi nhuận cao cho thấy hoạt động kinh doanh lành mạnh',
  'lowProfitMargin':
      '[CẢNH BÁO] Tỷ suất lợi nhuận thấp - nên xem xét lại chi phí và chiến lược giá',
  'goodCustomerRetention':
      '[OK] Tỷ lệ giữ chân khách hàng tốt cho thấy lòng trung thành của khách hàng',
  'improveCustomerRetention':
      '[CẢNH BÁO] Tỷ lệ giữ chân khách hàng có thể được cải thiện với các chiến lược tương tác tốt hơn',
  'lowStockAlert':
      '[CẢNH BÁO] {count} sản phẩm đang tồn kho thấp - nên cân nhắc nhập hàng',
  'consistentRevenue':
      '[OK] Doanh nghiệp đang tạo ra doanh thu ổn định với {orders} đơn hàng',
  'reportGeneratedBy': 'Báo cáo được tạo bởi',
  'generatedOn': 'Tạo vào',
};
