// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Web Firebase config from --dart-define (compile-time constants)
  // These are populated at build time via: flutter build web --dart-define-from-file=.env
  static const String _webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String _webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
  static const String _webMessagingSenderId =
      String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID');
  static const String _webProjectId =
      String.fromEnvironment('FIREBASE_WEB_PROJECT_ID');
  static const String _webAuthDomain =
      String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN');
  static const String _webStorageBucket =
      String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET');
  static const String _webMeasurementId =
      String.fromEnvironment('FIREBASE_WEB_MEASUREMENT_ID');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // For web: use dart-define constants (production) or fallback to dotenv (local dev)
      final apiKey = _webApiKey.isNotEmpty
          ? _webApiKey
          : dotenv.env['FIREBASE_WEB_API_KEY'] ?? '';
      final appId = _webAppId.isNotEmpty
          ? _webAppId
          : dotenv.env['FIREBASE_WEB_APP_ID'] ?? '';
      final messagingSenderId = _webMessagingSenderId.isNotEmpty
          ? _webMessagingSenderId
          : dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '';
      final projectId = _webProjectId.isNotEmpty
          ? _webProjectId
          : dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '';
      final authDomain = _webAuthDomain.isNotEmpty
          ? _webAuthDomain
          : dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'];
      final storageBucket = _webStorageBucket.isNotEmpty
          ? _webStorageBucket
          : dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'];
      final measurementId = _webMeasurementId.isNotEmpty
          ? _webMeasurementId
          : dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'];

      if (apiKey.isEmpty || appId.isEmpty || projectId.isEmpty) {
        throw Exception('Firebase Web configuration is missing. '
            'Build with: flutter build web --dart-define-from-file=.env');
      }

      return FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
        authDomain: authDomain,
        storageBucket: storageBucket,
        measurementId: measurementId,
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
          appId: dotenv.env['FIREBASE_ANDROID_APP_ID']!,
          messagingSenderId:
              dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID']!,
          projectId: dotenv.env['FIREBASE_ANDROID_PROJECT_ID']!,
          storageBucket: dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'],
        );
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
          appId: dotenv.env['FIREBASE_IOS_APP_ID']!,
          messagingSenderId: dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID']!,
          projectId: dotenv.env['FIREBASE_IOS_PROJECT_ID']!,
          storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'],
          androidClientId: dotenv.env['FIREBASE_IOS_ANDROID_CLIENT_ID'],
          iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'],
          iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'],
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
            'This platform is not supported for Firebase initialization via dotenv.');
    }
  }
}
