// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19PvPONLG89r_mW99GZJmSSt4JfWTa_E',
    appId: '1:413433346211:android:1155fb688243e1cd73a716',
    messagingSenderId: '413433346211',
    projectId: 'se121p11-gizmoglobe',
    storageBucket: 'se121p11-gizmoglobe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4dF121oymhtwO5gtkzDXZNEQDN9jaKw',
    appId: '1:413433346211:ios:5efab11c91b01c5973a716',
    messagingSenderId: '413433346211',
    projectId: 'se121p11-gizmoglobe',
    storageBucket: 'se121p11-gizmoglobe.firebasestorage.app',
    androidClientId: '413433346211-e37ub7irjajc7p3lnl8f7e3km9qbpus7.apps.googleusercontent.com',
    iosClientId: '413433346211-mhgq3nbgt2ht9vp8sn2l5g9e8u5tlb2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gizmoglobeRetailer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDBZZt21DTBGiDiE9VtWNyTTEIHFwzBo',
    appId: '1:413433346211:web:a637ea3bf231305373a716',
    messagingSenderId: '413433346211',
    projectId: 'se121p11-gizmoglobe',
    authDomain: 'se121p11-gizmoglobe.firebaseapp.com',
    storageBucket: 'se121p11-gizmoglobe.firebasestorage.app',
    measurementId: 'G-QC4HB14SR4',
  );

}